#!/bin/bash

set -e

apt-get update

apt-get install -y \
        autoconf \
        automake \
        autotools-dev \
        bc \
        bison \
        build-essential \
        curl \
        flex \
        gawk \
        gperf \
        libexpat-dev \
        libgmp-dev \
        libmpc-dev \
        libmpfr-dev \
        libtool \
        patchutils \
        texinfo \
        zlib1g-dev
